### ISSUE TITLE
Request - support for USB NIC adapters with ASIX AX88179 chipset and similar

### ISSUE THREAD

**Issue by alozzy** [xcp-ng/xcp-ng.github.io#10]
As per Olivier's request (see https://xcp-ng.org/2018/04/07/next-release-target-7-4-1/#comment-4), I'm opening this "issue" (just a feature request).

Would love to see XCP-ng support ASIX AX88179 chipset based USB NICs as Intel NUC Skull Canyon PCs are a favorite for testing environments but are limited to (1) on-board NIC. Many other hypervisors have been made to work with ASIX AX88179 chipset based USB NICs...

**Comment by necouchman** [comment]
I'm pretty sure this issue should actually be raised here: https://github.com/xcp-ng/xcp/issues.  This repo is for items specific to the web site, xcp-ng.github.io, not necessarily for feature requests in the actual software.

**Comment by fabz5** [comment]
FYI: I have opened a corresponding feature request on the github page for xcp-ng: https://github.com/xcp-ng/xcp/issues/52

**Comment by olivierlambert** [comment]
I'll close the repo issues (or archive the whole repo). Thanks for your feedback @fabz5
